-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS category;

ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS subcategory;

ALTER TABLE IF EXISTS public.campaign DROP CONSTRAINT IF EXISTS contact;



DROP TABLE IF EXISTS public.contacts;

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20),
    email character varying(50),
    PRIMARY KEY (contact_id)
);

DROP TABLE IF EXISTS public.campaign;

CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id integer NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying(50),
    description character varying(100),
    goal double precision NOT NULL,
    pledged double precision,
    outcome character varying(12),
    backers_count integer,
    country character varying(2),
    currency character varying(3),
    launched_date date,
    end_date date,
    category_id character varying(6),
    sub_category_id character varying(10),
    PRIMARY KEY (cf_id, contact_id)
);

DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(6) NOT NULL,
    category character varying(16) NOT NULL,
    PRIMARY KEY (category_id)
);

DROP TABLE IF EXISTS public.subcategory;

CREATE TABLE IF NOT EXISTS public.subcategory
(
    sub_category_id character varying(10) NOT NULL,
    subcategory character varying(25) NOT NULL,
    PRIMARY KEY (sub_category_id)
);

ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT category FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT subcategory FOREIGN KEY (sub_category_id)
    REFERENCES public.subcategory (sub_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD CONSTRAINT contact FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

select * from category
select * from subcategory
select * from contacts
select * from campaign